### ISSUE TITLE
Validation does not work properly in Version 4.0.0

### ISSUE THREAD

**Issue by kevinkendzia** [xdev-software/vaadin-chip-combobox#186] opened 2023-09-11 06:31 UTC
In Version 4.0.0 the validation of the ChipCombobox does not work if you use it with a binder and configure it with asRequired().
The field isn't marked red and doesn't show any error on tab change, but if you select a value and clear the box afterwards it seems to work again.

Could it be connected to the initial value setting?

Details on UI:

- simple form with ChipCombobox, Textfields, etc.
- bound with Binder
- shown in a dialog

**Comment by AB-xdev** [comment] 2023-09-13 08:17
The problem is caused by setting a ``HashSet`` as the component has an ``ArrayList`` as default. When comparing both collections a difference is detected, which should not be the case.

**Comment by AB-xdev** [comment] 2023-09-14 06:20
Fixed by https://github.com/xdev-software/vaadin-chip-combobox/commit/eb52f76fc29f5d2a60c9868d53fe673aaf78ac9a

**Closed by AB-xdev** 2023-09-14 06:20 UTC
Labels: bug
